### ISSUE TITLE
Does this repo need to be public?

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neetoui-codemod-v4#5]
If not then let's make it private.

**Comment by sumanranjanpanda** [comment]
cc: @amaldinesh7

**Comment by amaldinesh7** [comment]
This repo is created at the time of neetoUI v4 release. As the v3 to v4 migration codemod script is published as an NPM package, it required a public repo. We can make this private now as this migration is not needed. I suggest to keep the repo as the code might be useful for future migrations.

**Comment by sumanranjanpanda** [comment]
@neerajdotname _a. Either we close this open issue or move this repo to your account.
